function CDC

    disp('CDC is a computational toolbox')
    disp('It is developed by Duo CHAN at Harvard University')
    disp(' ')    
    disp('All functions in matrix preprocess and basic statistics') 
    disp('                   allows to specify dimensions and handles NAN')
    disp(' ')
    disp('Last update: 2018-08-10')
    disp(' ')
    disp('****************************************************************')
    disp('Functions include:')
    disp('****************************************************************')
    disp('Matrix preprocess:') 
    disp('    CDC_subset             % Subset the matrix according to criteria') 
    disp('    CDC_assign             % Assign the matrix according to criteria') 
    disp('    CDC_demean             % Remove the mean or cycle')
    disp('    CDC_detrend            % Remove linear trend or cycle of trends')
    disp(' ')
    disp(' ')
    disp('Basic Statistics:')
    disp('    CDC_mean_bt            % Compute mean')
    disp('    CDC_nansum             % Compute the summation')
    disp('    CDC_var                % Compute variance and covariance')
    disp('    CDC_var_bt             % Compute variance and covariance')
    disp('    CDC_std                % Compute standard error and normalize matrix')    
    disp('    CDC_corr               % Compute correlation')
    disp('    CDC_trend              % Compute linear trend or dependency')
    disp('    CDC_mask_mean          % Compute Mask or regional average')
    disp(' ')
    disp(' ')
    disp('Fitting:')
    disp('    CDC_TLS                % Total least square fit w./w.o. intercept')
    disp('    CDC_yorkfit            % York fit')
    disp('    CDC_yorkfit_bt         % York fit')
    disp(' ')
    disp(' ')
    disp('Smooth:')
    disp('    CDC_smooth2            % 2D Smoothing')
    disp('    CDC_conv2              % 2D convolusion')
    disp('    CDC_filter             % filter using fft')
    disp('    CDC_run                % running average')
    disp(' ')
    disp(' ')
    disp('Probability and inference:')   
    disp('    CDC_expolre_pspace     % Explore the parameter space of linear fit')
    disp('    CDC_prob               % Normalize probability density function')
    disp('    CDC_conf_int           % high dimensional confidence interval')
    disp('    CDC_mcmc_sampler       % MCMC sampler that takes in L in matrix form')
    disp(' ')
    disp(' ')
    disp('Earth Science:')  
    disp('    CDC_earth_grad         % Compute 2D gradient using finite difference')
    disp('    CDC_earth_grad_sphere  % Compute 2D gradient on spheric coordinate')
    disp('    CDC_earth_gw           % Compute geostrophic wind using SLP or HGT')
    disp('    CDC_earth_var          % Compute variance by remove cycle of mean and trend')
    disp('    CDC_get_season         % Get data within a season')
    disp('    CDC_EOF                % EOF analysis')
    disp('    CDC_earth_wave_flux    % Compute stationary wave activity flux')
    disp('    CDC_interp2            % 2D Interpolation')
    disp(' ')
    disp('GCM:')
    disp('    CDC_3D_profile_Gaussian % generate 3D heating profiles')
    disp(' ')
    disp(' ')
    disp('ICOADS:')
    disp('    CDC_merge_group        % merge results for individual groups into a table')
    disp(' ')
    disp('CMIP5:')
    disp('    CDC_get_reso           % Get resolution of CMIP5 models')
    disp(' ')
    disp(' ')
    disp('System:')
    disp('    CDC_ls                 % List files in a directory')
    disp('    CDC_parse              % Parse string')
    disp(' ')
    disp(' ')
    disp('Grid - Bin - Point:')
    disp('  These functions are not in this toolbox but are used in Homo Project ')
    disp('  They are listed here for quick reference ... ')
    disp(' ')
    disp('    HM_function_gridding')
    disp('     |_ HM_function_pnt2grd_3d')
    disp('     |_ HM_function_grd_average')
    disp(' ')
    disp('    HM_function_grd2pnt')
    disp('    HM_function_mask_average')
    disp('    HM_function_mean_period')
  

    
