function CDC

    disp('CDC is a computational toolbox')
    disp('It is developed by Duo CHAN at Harvard University')
    disp(' ')    
    disp('All functions in matrix preprocess and basic statistics') 
    disp('                   allows to specify dimensions and handles NAN')
    disp(' ')
    disp('Last update: 2018-08-10')
    disp(' ')
    disp('****************************************************************')
    disp('Functions include:')
    disp('****************************************************************')
    disp('Matrix preprocess:') 
    disp('    CDC_subset              % Subset the matrix according to criteria') 
    disp('    CDC_subset2             % Subset all variable in a struct according to criteria') 
    disp('    CDC_assign              % Assign the matrix according to criteria') 
    disp('    CDC_demean              % Remove the mean or cycle')
    disp('    CDC_detrend             % Remove linear trend or cycle of trends')
    disp(' ')
    disp(' ')
    disp('Basic Statistics:')
    disp('    CDC_mean_bt             % Compute mean')
    disp('    CDC_wmean               % weighted mean and variance and significance')
    disp('    CDC_nansum              % Compute the summation')
    disp('    CDC_var                 % Compute variance and covariance')
    disp('    CDC_var_bt              % Compute variance and covariance')
    disp('    CDC_std                 % Compute standard error and normalize matrix')    
    disp('    CDC_corr                % Compute correlation')
    disp('    CDC_cross_corr          % Lead-Lag correlation')
    disp('    CDC_Eff_DOF             % Effective degrees of freedom (batch method)')
    disp('    CDC_trend               % Compute linear trend or dependency')
    disp('    CDC_mask_mean           % Compute Mask or regional average')
    disp('    CDC_hemi_mean           % Compute hemispheric and global average')
    disp('    CDC_hemi_sum            % Compute hemispheric and global sum')
    disp('    CDC_pnt2glbmean         % Compute global mean from a list of points')
    disp('    CDC_hist2d              % 2D Histogram')
    disp('    CDC_bin1d               % 1D Histogram')
    disp('    CDC_phase_rnd           % Perform phase randomization to a time series')
    disp('    CDC_get_boot_order      % Generate an order of boostrapping indexing')
    disp(' ')
    disp(' ')
    disp('Simple Models')
    disp('    CDC_2box                % Two box climate model surface and deep ocean box')
    disp(' ')
    disp(' ')    
    disp('Fitting:')
    disp('    CDC_TLS                 % Total least square fit w./w.o. intercept')
    disp('    CDC_yorkfit             % York fit')
    disp('    CDC_yorkfit_bt          % York fit with boostrapping')
    disp(' ')
    disp(' ')
    disp('Smooth:')
    disp('    CDC_smooth2             % 2D Smoothing')
    disp('    CDC_conv2               % 2D convolusion')
    disp('    CDC_filter              % filter using fft')
    disp('    CDC_run                 % running average')
    disp(' ')
    disp(' ')
    disp('Probability and inference:')   
    disp('    CDC_expolre_pspace      % Explore the parameter space of linear fit')
    disp('    CDC_prob                % Normalize probability density function')
    disp('    CDC_conf_int            % high dimensional confidence interval')
    disp('    CDC_mcmc_sampler        % MCMC sampler that takes in L in matrix form')
    disp('    CDC_redrnd              % Genrate random red noise series')
    disp(' ')
    disp(' ')
    disp('Earth Science:')  
    disp('    CDC_earth_grad          % Compute 2D gradient using finite difference')
    disp('    CDC_earth_grad_sphere   % Compute 2D gradient on spheric coordinate')
    disp('    CDC_earth_gw            % Compute geostrophic wind using SLP or HGT')
    disp('    CDC_earth_var           % Compute variance by remove cycle of mean and trend')
    disp('    CDC_get_season          % Get data within a season')
    disp('    CDC_EOF                 % EOF analysis')
    disp('    CDC_earth_wave_flux     % Compute stationary wave activity flux')
    disp('    CDC_interp2             % 2D Interpolation')
    disp('    CDC_interp1             % Account for nan values')
    disp('    CDC_calculate_AMO       % Calculate AMO index using an SST input')
    disp('    CDC_generate_mask       % Generate regional mask on a grid')
    disp('    CDC_mon2sea             % Average monthly into seasonal values')
    disp('    CDC_day2mon             % Average daily into monthly values')
    disp(' ')
    disp('Thermodynamics:')
    disp('    CDC_es                  % Saturation water vapor pressure (hpa)')
    disp('    CDC_eq                  % Saturation specific humidity (kg/kg)')
    disp('    CDC_es_T                % Derivative of saturation water vapor pressure (hpa)')
    disp('    CDC_eq_T                % Derivative of saturation specific humidity (kg/kg)') 
    disp('    CDC_dew_point           % Calculate due point temperature')    
    disp('    CDC_wet_bulb            % Calculate wet bulb temperature Cooling by evaporating water') 
    disp('    CDC_wet_bulb_stull      % Calculate wet bulb temperature Stull formula')
    disp(' ')
    disp('Run and process GCM:')
    disp('    CDC_3D_profile_Gaussian % generate 3D heating profiles')
    disp(' ')
    disp(' ')
    disp('Gridding, regridding, or reshape table:')
    disp('    CDC_grd2pnt             % Subset from a gridded data')
    disp('    CDC_pnt2grd             % Gridding')
    disp('    CDC_interp_high_reso    % Regridding')
    disp('    CDC_average_grid        % Regridding')
    disp('    CDC_merge_group         % Merge results for individual groups into a table')
    disp('    CDC_trim_years          % Subset the year dimension of a dataset')
    disp(' ')
    disp('Climate Variability')
    disp('    CDC_AMO                 $ Calculate Atlantic Multidecadal Oscillation Index')
    disp(' ')
    disp('Other Temperature dataset:')
    disp('    >> SST: ')
    disp('        CDC_load_HadSST4       % load HadSST4')
    disp('        CDC_load_ERSST5        % load ERSST5')
    disp('        CDC_load_COBESST2      % load COBESST2')
    disp('        CDC_load_HadISST2      % load HadISST2')
    disp('                                        ')
    disp('        CDC_load_HadSST3       % load HadSST3')
    disp('        CDC_load_HadISST       % load HadISST1')
    disp('        CDC_load_HadISST1b     % load HadISST1b')
    disp('                                        ')
    disp('    >> Land Temperatures: ')    
    disp('        CDC_load_CRUTEM5       % load CRUTEM5')
    disp('        CDC_load_GISTEMP       % load NASA GISTEMP')
    disp('        CDC_load_Berkeley      % load Berkeley Earth Land Temperature')
    disp('                                        ')
    disp('    >> Combined Temperatures: ')    
    disp('        CDC_load_HadCRUT5      % load HadCRUT5')
    disp('        CDC_load_NOAATEMP      % load NOAA Global Temperature')
    disp(' ')
    disp('    >> Supporting functions: ')
    disp('        CDC_other_temp_dir         % TODO: directory of temperature data')
    disp('        CDC_common_time_interval   % TODO: common years to be analyzed')  
    disp(' ')
    disp(' ')
    disp('CMIP:')
    disp('    CDC_get_reso           % Get resolution of CMIP5 models')
    disp('    CDC_get_reso_CMIP6     % Get resolution of CMIP6 models')
    disp(' ')
    disp(' ')
    disp('System:')
    disp('    CDC_ls                 % List files in a directory, can subset for file types and key words')
    disp('    CDC_parse              % Parse string')
    disp(' ' )
    disp('PAPER WRITING:')
    disp('    CDC_clean_bib          % clean up and combine bib files')
    disp(' ')
    disp(' ')
    disp('Misc')
    disp('    HM_function_mean_period')
  

    
